import Link from "next/link";

export default function TermsPage() {
  return (
    <>
      <header className="site-header">
        <div className="container header-inner">
          <Link className="brand" href="/" aria-label="TimeCam home">
            <img className="brand-logo" src="/images/TimeCamTextLOGO.png" alt="TimeCam" />
            <span className="brand-name">TimeCam</span>
          </Link>
          <nav className="nav">
            <Link href="/" className="nav-link">Home</Link>
            <Link href="/support" className="nav-link">Support</Link>
            <Link href="/privacy" className="nav-link">Privacy</Link>
            <Link href="/terms" className="nav-link is-active">Terms</Link>
          </nav>
          <a className="button nav-cta" href="https://apps.apple.com">
            Download on the App Store
          </a>
        </div>
      </header>

      <main className="container">
        <section className="hero compact">
          <p className="eyebrow">Terms</p>
          <h1>TimeCam – End User License Agreement (Custom EULA)</h1>
          <p className="fineprint muted">
            Last updated: <span id="termsUpdated">16-01-26</span>
          </p>
        </section>

        <section className="section card">
          <p className="muted">
            This End User License Agreement (“EULA”) is a Custom EULA between you (“User”) and TimeCam (“Application
            Provider”, “we”, “us”), and is supplemental to Apple’s Licensed Application End User License Agreement
            (“Standard EULA”).
          </p>
          <p className="muted">
            By downloading or using TimeCam, you acknowledge that you have read and agree to be bound by Apple’s Standard
            EULA, in addition to the terms below. If there is any conflict, Apple’s Standard EULA shall govern where
            required by Apple policy.
          </p>
        </section>

        <section className="section card">
          <h2>1. Scope of License</h2>
          <p className="muted">
            TimeCam is licensed, not sold, to you for use on Apple-branded devices that you own or control, in accordance
            with Apple’s Standard EULA and App Store Usage Rules.
          </p>
        </section>

        <section className="section card">
          <h2>2. Description of the Application</h2>
          <p className="muted">
            TimeCam is an AI-powered application that generates artistic, illustrative images and videos inspired by
            historical periods, locations, or speculative timelines based on user-provided photos and inputs.
          </p>
          <p className="muted">Generated content:</p>
          <ul className="list">
            <li>Is not guaranteed to be historically, geographically, or factually accurate</li>
            <li>Is intended for creative, entertainment, and illustrative purposes only</li>
            <li>Must not be relied upon as factual evidence</li>
          </ul>
        </section>

        <section className="section card">
          <h2>3. AI-Generated Content Disclaimer</h2>
          <p className="muted">You acknowledge and agree that:</p>
          <ul className="list">
            <li>Outputs are generated by artificial intelligence systems</li>
            <li>Results may be inaccurate, fictional, or misleading</li>
            <li>TimeCam makes no guarantees regarding accuracy, uniqueness, or realism</li>
            <li>You use all generated content at your own risk</li>
          </ul>
          <p className="muted">TimeCam is not responsible for decisions made based on AI-generated outputs.</p>
        </section>

        <section className="section card">
          <h2>4. Credits, Purchases &amp; Subscriptions</h2>
          <p className="muted">TimeCam may offer:</p>
          <ul className="list">
            <li>Free credits</li>
            <li>Paid credit top-ups</li>
            <li>Auto-renewing subscriptions</li>
          </ul>
          <p className="muted">Credits:</p>
          <ul className="list">
            <li>Have no monetary value</li>
            <li>Are non-transferable</li>
            <li>Are non-refundable, except where required by law</li>
          </ul>
          <p className="muted">
            Subscriptions are managed through Apple and may be cancelled via the App Store account settings.
          </p>
        </section>

        <section className="section card">
          <h2>5. User Content</h2>
          <p className="muted">You retain ownership of images you upload.</p>
          <p className="muted">
            By using TimeCam, you grant us a limited, non-exclusive, royalty-free license to process your content solely
            for the purpose of operating and improving the app.
          </p>
        </section>

        <section className="section card">
          <h2>6. Location Data</h2>
          <p className="muted">TimeCam may use location data:</p>
          <ul className="list">
            <li>To identify nearby historical events</li>
            <li>To enhance image and video generation</li>
          </ul>
          <p className="muted">
            Location data is not used for tracking or advertising and is handled in accordance with our Privacy Policy.
          </p>
        </section>

        <section className="section card">
          <h2>7. Acceptable Use</h2>
          <p className="muted">You agree not to use TimeCam to:</p>
          <ul className="list">
            <li>Generate illegal or harmful content</li>
            <li>Misrepresent AI-generated content as factual or historical proof</li>
            <li>Infringe on the rights of others</li>
            <li>Abuse, exploit, or attempt to bypass app means, credits, or systems</li>
          </ul>
        </section>

        <section className="section card">
          <h2>8. Termination</h2>
          <p className="muted">This EULA is effective until terminated.</p>
          <p className="muted">
            Your rights terminate automatically if you fail to comply with these terms or Apple’s Standard EULA.
          </p>
        </section>

        <section className="section card">
          <h2>9. Warranty Disclaimer &amp; Limitation of Liability</h2>
          <p className="muted">
            TimeCam is provided “AS IS” and “AS AVAILABLE”, in line with Apple’s Standard EULA. To the maximum extent
            permitted by law, TimeCam disclaims all warranties and shall not be liable for any indirect, incidental, or
            consequential damages arising from use of the app.
          </p>
        </section>

        <section className="section card">
          <h2>10. Governing Law</h2>
          <p className="muted">
            For users in the UK and EU, this EULA is governed by the laws of your country of residence, in accordance with
            Apple’s Standard EULA provisions.
          </p>
        </section>

        <section className="section card">
          <h2>11. Contact</h2>
          <p className="muted">For questions or support, contact:</p>
          <ul className="list">
            <li>Email: support@timecam.ai</li>
            <li>Website: <span className="mono">https://timecam.ai</span></li>
          </ul>
        </section>
      </main>

      <footer className="site-footer">
        <div className="container footer-inner">
          <div>
            <span className="brand-name">TimeCam</span>
            <p className="muted">Support: <a href="mailto:support@timecam.ai">support@timecam.ai</a></p>
          </div>
          <div className="footer-links">
            <Link href="/support">Support</Link>
            <Link href="/privacy">Privacy</Link>
            <Link href="/terms">Terms</Link>
            <Link href="/">Home</Link>
          </div>
          <div className="muted">© <span id="year"></span> TimeCam</div>
        </div>
      </footer>
    </>
  );
}
